#!/usr/bin/env bash
########################################
####     ALIAS
########################################

#### OS ALIASES ####
alias ll='ls -lGh $@'
alias p4='ping 4.2.2.2'
# Addressed in bashrch.sh, as this doesn't load properly
# source ~/.dotfiles/private/*repos*.sh
alias repofresh='~/.dotfiles/script/refresh_repos.sh'
alias resource='source ~/.bash_profile'

function enable_ntfs() {
    VOLUME_NAME=$1
    VOLUME_UUID=`diskutil info \`diskutil list|grep -e "${VOLUME_NAME}"|awk '{print $NF}'\`|grep UUID|awk '{print $NF}'`
    FSTAB_STR="UUID=${VOLUME_UUID} none ntfs rw,auto,nobrowse"
    sudo cat ${FSTAB_STR} > /etc/fstab
    diskutil umount "${VOLUME_NAME}"
    diskutil mount "${VOLUME_NAME}"
}

#### GIT ALIASES ####
alias gs='git status'
alias gsd='echo; ~/.git-branch-status -va; echo; git status; echo; git log -1; echo; echo "CURRENT TIME: `date`"; echo'
alias gbc="git status | awk '{print \$3}' | head -n 1 | pbcopy"
alias gboth='git checkout master && git pull origin master && git checkout develop && git pull origin develop'

function local_git_check() {
  for repo in $(locate .git | grep git$ | grep -v "Homebrew" | sed 's/\/.git//g')
  do 
    cd $repo
    git pull --all
    res=$(gsd)
    if [[ $res != *up-to-date* ]] || [[ $res == *"Untracked files"* ]] || [[ $res == *"Changes not staged"*  ]]
    then 
      gsd
      break
    fi
  done
}
#### APP ALIASES ####
alias f='fuck'

function ssh_partner_sftp() {
  PARTNER_CODE=$1
  SFTP_SERVER=$(host sftp.$PARTNER_CODE.shoprunner.net | tail -n1 | cut -d. -f1)
  ssh $SFTP_SERVER
}
