#!/usr/bin/env bash
########################################
####     SOURCE
########################################

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
    fi
fi

complete -C /opt/homebrew/bin/vault vault

