#!/usr/bin/env bash
########################################
####     ALIAS
########################################

#### OS ALIASES ####
alias ll='ls -lGh $@'
alias resource='source ~/.bash_profile'

#### GIT ALIASES ####
alias gs='git status'
alias gsd='echo; ~/.git-branch-status -va; echo; git status; echo; git log -1; echo; echo "CURRENT TIME: `date`"; echo'
alias gbc="git status | awk '{print \$3}' | head -n 1 | pbcopy"
