#!/usr/bin/env bash
########################################
####     BASHOPTS
########################################

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
export HISTSIZE=1000
export HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize


########################################
####     ENV
########################################
export EDITOR='vim'
export HISTTIMEFORMAT="%D %T "
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
export REPODIR=~/dev

########################################
####     ALIAS
########################################

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_alias, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_alias ]; then
    . ~/.bash_alias
fi

# Private aliases, expecting multiple files and folders
if [ -d ~/.dotfiles/private ]; then
    # Loop folders
    PRIVATE_FOLDERS=`ls -p ~/.dotfiles/private | grep -e "/$"`
    for FOLDER in ${PRIVATE_FOLDERS}; do
        # Loop files in folder
        unset PRIVATE_DOTFILES
        PRIVATE_DOTFILES=`ls -pf ~/.dotfiles/private/${FOLDER%?} | grep -v "/"`
        for DOTFILE in ${PRIVATE_DOTFILES}; do
            . ~/.dotfiles/private/${FOLDER%?}/${DOTFILE}
        done
    done
fi

# enable bash completion for git
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
  __GIT_PROMPT_DIR=$(brew --prefix)/opt/bash-git-prompt/share
  source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
fi

# tabtab source for yo package
# uninstall by removing these lines or running `tabtab uninstall yo`
[ -f /usr/local/lib/node_modules/yo/node_modules/tabtab/.completions/yo.bash ] && . /usr/local/lib/node_modules/yo/node_modules/tabtab/.completions/yo.bash

export PATH=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin:$PATH

export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"

set -o vi
