#!/usr/bin/env bash
########################################
####     ALIAS
########################################

#### OS ALIASES ####
alias ll='ls -lGh $@'
alias p4='ping 4.2.2.2'
# Addressed in bashrch.sh, as this doesn't load properly
# source ~/.dotfiles/private/*repos*.sh
alias repofresh='~/.dotfiles/script/refresh_repos.sh'
alias resource='source ~/.bash_profile'

#### GIT ALIASES ####
alias gs='git status'
alias gsd='echo; ~/.git-branch-status -va; echo; git status; echo; git log -1; echo; echo "CURRENT TIME: `date`"; echo'
alias gbc="git status | awk '{print \$3}' | head -n 1 | pbcopy"
alias gboth='git checkout master && git pull origin master && git checkout develop && git pull origin develop'
