"turn on line numbers
set number

" *Search Options*
" Ignore case when searching unless mixed case is used in search.
set ignorecase
set smartcase

nnoremap * /\<<C-R>=expand('<cword>')<CR>\><CR>
nnoremap # ?\<<C-R>=expand('<cword>')<CR>\><CR>

" Search incramentally while typing
set incsearch
" Highlight search by default
set hlsearch

" Use %%\ to expand to buffer's directory not pwd
cabbr <expr> %% expand('%:p:h')

" Show the matching structure when cursoring over it.
set showmatch

" Set tabs to be 2 spaces
set tabstop=2
set shiftwidth=2
set expandtab

set nocompatible
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'udalov/kotlin-vim'
Plugin 'leafgarland/typescript-vim'

call vundle#end()            " required
filetype plugin indent on    " required

" Need for Vimwiki (and possibly others)
syntax on

set backspace=2

" Load all plugins now.
" Plugins need to be added to runtimepath before helptags can be generated.
packloadall
" Load all of the helptags now, after plugins have been loaded.
" All messages and errors will be ignored.
silent! helptags ALL

let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'python': [
\       'remove_trailing_lines',
\       'isort',
\       'black',
\   ],
\   'javascript': ['eslint'],
\}


" Set this veriable to 1 to fix files when you save them.
let g:ale_fix_on_save = 1
